spring.application.name=demo
server.port=8080
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topic=demo-topic
spring.data.mongodb.uri=mongodb://localhost:27017/demo

# Expose health (and optionally info) over HTTP
# (health and info are exposed by default, so this is optional)
management.endpoints.web.exposure.include=health,info

# Show detailed health in dev (remove/lock down for prod)
management.endpoint.health.show-details=always

# Enable liveness/readiness subprobes (nice for Docker/K8s)
management.endpoint.health.probes.enabled=true


